### ISSUE TITLE
restrict bot to certain channel(s)

### ISSUE THREAD

**Issue by khavernathy** [khavernathy/ghost_bot#1]
@GuardianGR00T asked:

**Is there any way you could make it to where we can move it to it's own channel within the server?**

---

the only way i know of is to change the settings for each text channel you don't want the bot in, i.e.

1) click the "settings" cog for the channel
2) click permissions
3) click (+) on roles/members
4) add ghost_bot, and click the red X on every option

I don't think discord has come up with an easier way, yet, see e.g. here: https://support.discord.com/hc/en-us/community/posts/360045778711-Restrict-bots-to-certain-channels-

**Comment by shirobachi** [comment]
I am not sure, but it looks to me like a discord admin problem. I mean that you should just remove bot permission to see or/and write in channel what you don't want. If you do, that bot will not see messages on that channel (or/and will not be able to write)
