### ISSUE TITLE
Updated evidence

### ISSUE THREAD

**Issue by GustavoSchip** [khavernathy/ghost_bot#3]
There are new evidences! Can u update the bot?

**Comment by GILLESMaster** [comment]
I updated this source and u can invite the updated bot with 

[https://discord.com/api/oauth2/authorize?client_id=884660463323971614&permissions=240518507584&scope=bot](https://discord.com/api/oauth2/authorize?client_id=884660463323971614&permissions=240518507584&scope=bot)

**Comment by khavernathy** [comment]
will do.

**Comment by khavernathy** [comment]
done. Added the new ghost also
